title: "My Blog Page"
author: "Jovanni Catalan Hurtado"
description: "Blog page for ST 558 Data Science with R." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.
# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "catalanhurtadoj@guilford.edu"
twitter_username: ""
github_username: ""
linkedin_username: ""
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
